# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Extract NPM tag from release
        id: get_npm_tag
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            echo "NPM_TAG=beta" >> $GITHUB_OUTPUT
          else
            VERSION=${{ steps.get_version.outputs.VERSION }}
            if [[ "$VERSION" == *"-alpha"* ]]; then
              echo "NPM_TAG=alpha" >> $GITHUB_OUTPUT
            elif [[ "$VERSION" == *"-beta"* ]]; then
              echo "NPM_TAG=beta" >> $GITHUB_OUTPUT
            elif [[ "$VERSION" == *"-rc"* ]]; then
              echo "NPM_TAG=rc" >> $GITHUB_OUTPUT
            else
              RELEASE_TAG="${{ github.event.release.tag_name }}"
              if [[ "$RELEASE_TAG" != "v"* && "$RELEASE_TAG" != "" ]]; then
                echo "NPM_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
              else
                echo "NPM_TAG=latest" >> $GITHUB_OUTPUT
              fi
            fi
          fi
      - run: pnpm install --frozen-lockfile
      - name: Update version in package.json
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.VERSION }}" | sed 's/^v//')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
          echo "Update version to $VERSION"
          cat package.json | grep version
      - name: Publish with custom tag
        run: pnpm publish --tag ${{ steps.get_npm_tag.outputs.NPM_TAG }} --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
